- name: Update plugins
  command: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/ install-plugin {{ item }}
  with_items: '{{ plugins_updates.stdout_lines }}'
  when: plugins_updates.stdout_lines
  ignore_errors: yes
  notify: restart jenkins
