---
- name: Ensure URL prefix is present in Jenkins config.
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^JENKINS_ARGS='
    regexp: '^JENKINS_ARGS\+=" --prefix='
    line: 'JENKINS_ARGS+=" --prefix={{ jenkins_url_prefix }}"'
  register: jenkins_init_prefix

- name: modify jenkins defaults to fix cli calls
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    line: 'JAVA_ARGS+=" -Dhudson.diyChunking=false "'
  register: jenkins_init_cli_fix

- name: modify jenkins defaults to set loose content security policy
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    line: JAVA_ARGS+=" -Dhudson.model.DirectoryBrowserSupport.CSP=\"sandbox allow-scripts allow-same-origin; default-src 'none'; img-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; font-src 'self'\""
  register: jenkins_init_csp_fix

- name: wait for config.xml to be present
  wait_for:
    path: "/var/lib/jenkins/config.xml"
    state: present
    delay: 2
    timeout: 30

- name: disable CSRF crumb issuer (prevents cli from working)
  replace:
    dest: "/var/lib/jenkins/config.xml"
    regexp: '<crumbIssuer (.|\n)*</crumbIssuer>'
    replace: ''
  register: jenkins_init_crumb_issuer

- name: Set HTTP port in Jenkins config.
  lineinfile:
    backrefs: yes
    dest: "{{ jenkins_init_file }}"
    regexp: '^{{ jenkins_http_port_param }}='
    line: '{{ jenkins_http_port_param }}={{ jenkins_http_port }}'
  register: jenkins_http_config

- name: Immediately restart Jenkins on config changes.
  service: name=jenkins state=restarted
  when: >
    jenkins_init_prefix.changed or
    jenkins_init_cli_fix.changed or
    jenkins_init_crumb_issuer.changed or
    jenkins_init_csp_fix.changed or
    jenkins_http_config.changed

- include: check-availability.yml
