---
- name: Ensure URL prefix is present in Jenkins config.
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    insertafter: '^JENKINS_ARGS='
    line: 'JENKINS_ARGS="$JENKINS_ARGS --prefix={{ jenkins_url_prefix }}"'
  when: jenkins_url_prefix|default("") != ""
  register: jenkins_init_prefix

- name: modify jenkins defaults to change tmp directory
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    line: 'JENKINS_JAVA_OPTIONS="$JENKINS_JAVA_OPTIONS -Djava.io.tmpdir=$JENKINS_HOME/tmp "'
  register: jenkins_init_tmpdir_fix

- name: modify jenkins defaults to fix cli calls
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    line: 'JENKINS_JAVA_OPTIONS="$JENKINS_JAVA_OPTIONS -Dhudson.diyChunking=false "'
  register: jenkins_init_cli_fix

- name: modify jenkins defaults to set loose content security policy
  lineinfile:
    dest: "{{ jenkins_init_file }}"
    line: JENKINS_JAVA_OPTIONS="$JENKINS_JAVA_OPTIONS -Dhudson.model.DirectoryBrowserSupport.CSP=\"sandbox allow-scripts allow-same-origin; default-src 'none'; img-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; font-src 'self'\""
  register: jenkins_init_csp_fix

- name: Set HTTP port in Jenkins config.
  lineinfile:
    backrefs: yes
    dest: "{{ jenkins_init_file }}"
    regexp: '^{{ jenkins_http_port_param }}='
    line: '{{ jenkins_http_port_param }}={{ jenkins_http_port }}'
  register: jenkins_http_config

- name: Ensure Jenkins is started and runs on startup.
  service: name=jenkins state=started enabled=yes

- name: wait for config.xml to be present
  wait_for:
    path: "{{ jenkins_config_file }}"
    state: present
    delay: 2
    timeout: 30

- name: disable CSRF crumb issuer (prevents cli from working)
  replace:
    dest: "{{ jenkins_config_file }}"
    regexp: '<crumbIssuer (.|\n)*</crumbIssuer>'
    replace: ''
  register: jenkins_init_crumb_issuer

- name: Immediately restart Jenkins on config changes.
  service: name=jenkins state=restarted
  when: >
    jenkins_init_prefix.changed or
    jenkins_init_tmpdir_fix.changed or
    jenkins_init_cli_fix.changed or
    jenkins_init_crumb_issuer.changed or
    jenkins_init_csp_fix.changed or
    jenkins_http_config.changed

- include: check-availability.yml
